# Generated by Django 2.2.4 on 2019-12-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0004_paquete_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_local', models.BooleanField(blank=True, null=True, verbose_name='Casa Local')),
                ('hostales', models.BooleanField(blank=True, null=True, verbose_name='Hostales')),
                ('hotel', models.BooleanField(blank=True, null=True, verbose_name='Hotel')),
                ('compania', models.PositiveSmallIntegerField(choices=[('1', 'Solo'), ('2', 'Pareja'), ('3', 'Familia')])),
                ('adultos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Adultos')),
                ('ninos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Niños')),
                ('text', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.Paquete')),
            ],
        ),
    ]
