# Generated by Django 2.2.4 on 2020-03-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0005_auto_20200309_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.PositiveSmallIntegerField(choices=[(1, 'Solo'), (2, 'Pareja'), (3, 'Familia')])),
                ('adultos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Adultos')),
                ('ninos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Niños')),
                ('alojamiento', models.PositiveSmallIntegerField(choices=[(1, 'Casa local'), (2, 'Hostal'), (3, 'Hotel')])),
                ('text', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('comprobante_presupuesto', models.FileField(null=True, upload_to='billing')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.Paquete')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
