# Generated by Django 2.2.4 on 2019-12-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['titulo']},
        ),
        migrations.RemoveField(
            model_name='billing',
            name='casa_local',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='hostales',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='hotel',
        ),
        migrations.AddField(
            model_name='billing',
            name='alojamiento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Casa local'), (2, 'Hostal'), (3, 'Hotel')], default=1),
        ),
        migrations.AlterField(
            model_name='billing',
            name='compania',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Solo'), (2, 'Pareja'), (3, 'Familia')]),
        ),
    ]
