# Generated by Django 2.2.4 on 2019-12-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20191209_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='alojamiento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Casa local'), (2, 'Hostal'), (3, 'Hotel')]),
        ),
    ]
