# Generated by Django 2.2.4 on 2020-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20191209_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='comprobante_presupuesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
