# Generated by Django 2.2.4 on 2019-11-19 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('destinos', models.CharField(max_length=500)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('duracion', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('fotos_portada', models.FileField(upload_to='img/')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
    ]
