# Generated by Django 2.2.4 on 2019-11-20 19:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('destinos', models.CharField(max_length=500)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('duracion', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('fotos_portada', models.FileField(upload_to='img/')),
                ('slug', models.SlugField(max_length=40)),
                ('guia', models.BooleanField(blank=True, null=True, verbose_name='Guide')),
                ('chofer', models.BooleanField(blank=True, null=True, verbose_name='Driver')),
                ('traslado', models.BooleanField(blank=True, null=True, verbose_name='Airport transfer')),
            ],
        ),
    ]
