# Generated by Django 2.2.4 on 2019-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
