# Generated by Django 2.2.4 on 2019-11-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paquetes',
            new_name='Paquete',
        ),
    ]
