# Generated by Django 2.2.4 on 2019-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_auto_20191119_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='chofer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='guia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='traslado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Airport transfer'),
        ),
    ]
