# Generated by Django 2.2.4 on 2019-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_paquete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='round',
            field=models.BooleanField(default=False),
        ),
    ]
