# Generated by Django 2.2.4 on 2019-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_paquete_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
