# Generated by Django 2.2.4 on 2020-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_paquete_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosInlcuidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Servicio incluido',
                'verbose_name_plural': 'Servicios incluidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServiciosNoInlcuidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Servicio No incluido',
                'verbose_name_plural': 'Servicios No incluidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='noservicios',
            field=models.ManyToManyField(related_name='get_not_services', to='destinos.ServiciosNoInlcuidos', verbose_name='Servicios No Inlcuidos'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(related_name='get_services', to='destinos.ServiciosInlcuidos', verbose_name='Servicios Inlcuidos'),
        ),
    ]
